name: "报告权限不合理使用等有关问题"
description: "报告本人在社区中可能存在的不合理使用权限问题"

labels: ["report","wait for review"]

body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我保证这些信息真实有效，不存在诬告陷害行为"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 事件发生在哪个社区？
    description: "例如 Hex-Dragon/PCL2"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 阐述为什么你认为这个行为是不合理的
    description: "详细描述你认为不合理的理由。"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 你认为正确的行为应该是怎么样的？
  validations:
    required: false
