name: Download and Upload to Release (Zip Split)

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      run: |
        curl -ILo ad.jar https://media.forgecdn.net/files/5829/843/AdHooks-1.20.1-10.1.2.1-build.0895.jar
